version: '3.8'
services:
  nginx:
    image: cntzoufras/admin-nginx:latest
    ports:
      - "80:80"   # Redirect HTTP to HTTPS
      - "443:443" # SSL port
    volumes:
      - ./template/nginx.prod.conf:/etc/nginx/nginx.conf
      - /etc/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - /etc/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    depends_on:
      - proxy
    networks:
      - webnet

  proxy:
    image: cntzoufras/admin-proxy:latest
    ports:
      - "5000:5000"
    networks:
      - webnet

networks:
  webnet:
