volumes:
  react_node_modules:
services:
  react:
    image: node:20
    working_dir: /surveycat
    ports:
      - "3000:3000"
    volumes:
      - .:/surveycat
      - react_node_modules:/surveycat/node_modules
      - ./local-docker-entry.sh:/local-docker-entry.sh
    command: ["sh", "-e"]
    entrypoint: /local-docker-entry.sh
