volumes:
  react_node_modules:
services:
  react:
    image: node:20
    working_dir: /surveycat
    ports:
      - "3000:3000"
    volumes:
      - react_node_modules:/surveycat/node_modules
    command: ["sh", "-e"]