version: '3.8'
services:
  react:
    build:
      context: .
      dockerfile: template/Dockerfile.prod
    networks:
      - webnet
  proxy:
    build:
      context: .
      dockerfile: proxy/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - webnet
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - /etc/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - /etc/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    depends_on:
      - react
      - proxy
    networks:
      - webnet
networks:
  webnet: