version: '3.8'
services:
  react:
    build:
      context: .
      dockerfile: template/Dockerfile.prod
    ports:
      - "80:80"
  proxy:
    build:
      context: .
      dockerfile: proxy/Dockerfile
    ports:
      - "5000:5000"