name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and Deploy
      run: |
        ssh -p 54222 -o StrictHostKeyChecking=no -i ${{ secrets.FRONT_SECRET }} cntzoufras@snf-893977.vm.okeanos.grnet.gr 'cd /var/www/html/surveycat-front && git pull && docker-compose up -d --build'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.FRONT_SECRET }}
