name: Deploy Surveycat React front React with Nginx

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_VERSION: 3.0
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
      
    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GH_FRONT_SECRET }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -p 54222 snf-893977.vm.okeanos.grnet.gr >> ~/.ssh/known_hosts

    # Cache Docker layers
    # - name: Cache Docker layers
    #   uses: actions/cache@v3
    #   with:
    #     path: /tmp/.buildx-cache
    #     key: ${{ runner.os }}-buildx-${{ github.sha }}
    #     restore-keys: |
    #       ${{ runner.os }}-buildx-
    
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build and push Docker images to Docker Hub
      run: |
        echo "${{ secrets.SURVEYCAT_FRONT_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        
        # Build the Docker image
        docker-compose -f docker-compose.prod.yml build --build-arg IMAGE_VERSION=$IMAGE_VERSION
          
        # Tag and push the image to Docker Hub
        docker tag cntzoufras/admin-nginx:$IMAGE_VERSION cntzoufras/admin-nginx:$IMAGE_VERSION
        docker-compose -f docker-compose.prod.yml push nginx
      env:
          IMAGE_VERSION: 3.0
          
    - name: Deploy to Production Server Using Docker Hub Image
      run: |
        ssh -p 54222 -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key cntzoufras_deploy@snf-893977.vm.okeanos.grnet.gr '
          export IMAGE_VERSION=$IMAGE_VERSION && \
          cd /var/www/surveycat_front && \
          docker-compose -f docker-compose.prod.yml down --volumes && \
          docker-compose -f docker-compose.prod.yml pull nginx && \
          echo "REACT_APP_API_URL=https://snf-893977.vm.okeanos.grnet.gr/api" > .env && \
          echo "REACT_APP_BASE_URL=https://snf-893977.vm.okeanos.grnet.gr" >> .env && \
          echo "REACT_APP_IMAGE_BASE_URL=https://snf-893977.vm.okeanos.grnet.gr/images" >> .env && \
          docker-compose -f docker-compose.prod.yml up -d
        '
      env:
          IMAGE_VERSION: 3.0
